---
fail_fast: true
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: no-commit-to-branch
        args: [--branch, main]
