---
branches:
  - name: main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - "@semantic-release/git"
  - "@semantic-release/github"
verifyConditions:
  - "@semantic-release/changelog"
  - "@semantic-release/github"
prepare:
  - "@semantic-release/changelog"
  - - "@semantic-release/git"
    - message: "chore(release): ${nextRelease.version} \n\n${nextRelease.notes}"
publish:
  - - "@semantic-release/github"
    - assets:
      - path: web-ext-artifacts/firefox-subseven-theme.xpi
success: false
fail: false
tagFormat: "v${version}"
