---
branches:
  - name: main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
  - - "@semantic-release/github"
    - assets:
      - path: action-web-ext/firefox-subseven-theme.xpi
verifyConditions:
  - "@semantic-release/changelog"
  - "@semantic-release/github"
prepare:
  - "@semantic-release/changelog"
  - - "@semantic-release/git"
    - message: "chore(release): ${nextRelease.version} \n\n${nextRelease.notes}"
publish:
  - "@semantic-release/github"
success: false
fail: false
tagFormat: "${version}"
