---
name: 'Release'
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "web-ext lint"
        if: github.event_name == 'pull_request'
        uses: kewisch/action-web-ext@v1
        with:
          cmd: lint
          source: src
          channel: unlisted

      - name: "web-ext build"
        if: github.event_name == 'push'
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: src
          filename: "firefox-subseven-theme.xpi"
          #ignoreFiles: '[ "" ]'

      - name: "Upload Artifact"
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: firefox-subseven-theme.xpi
          path: ${{ steps.web-ext-build.outputs.target }}
